#
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
#

#
# Inject MDC info into log entries
#
logging.pattern.level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

#
# Opt-in to actuator endpoints. This doesn't appear to work
# despite the documentation to the contrary.
#
management.endpoints:
  enabled-by-default: false
management.endpoint:
  info.enabled: true
  health.enabled: true
  metrics.enabled: true

#
# This works instead.
#
  jmx.exposure.include:
    - info
    - health
    - metrics
  web.exposure.include:
    - info
    - health
    - metrics

spring:
  application:
    name: Example Service

#
# configuration that depends on the runtime environment should be configured via the
# environment or command line arguments. See https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables
#
