
FROM centos

# Set TimeZone to UTC
RUN mv /etc/localtime /etc/localtime.bak
RUN ln -s /usr/share/zoneinfo/UTC /etc/localtime

# Must have utilities
#RUN yum install -y wget unzip
#RUN yum install -y openssh-clients
RUN yum install -y java-11-openjdk 

WORKDIR /usr/local

#
# Dependencies
#
#ARG JDK=jdk-11.0.2
#ARG ARTIFACT=openjdk-11.0.2_linux-x64_bin.tar.gz

#ARG REPO=http://ci-artifacts.devops.fds.com/artifactory
#
# Download and install
#
#RUN wget -O ${ARTIFACT} ${REPO}/binrepo/java11/${ARTIFACT} && \
#    tar -xf ${ARTIFACT} && \
#    rm ${ARTIFACT}
 
#
# Install SpringBoot executable
#
COPY /maven/service-bin.jar bin

#
# Environment
#
#ENV JAVA_HOME /usr/local/${JDK}
ENV JAVA_HOME $(dirname $(dirname $(readlink $(readlink $(which javac)))))
ENV PATH $PATH:$JAVA_HOME/bin

#
# Launch
#
EXPOSE 8080 8080
CMD ["java", "-jar", "bin/service-bin.jar"]
